/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2014-08-20 17:31:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class controller_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>reg</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String name=request.getParameter("name");
String addr=request.getParameter("addr");
String phno=request.getParameter("phno");
String pass=request.getParameter("password");
String email=request.getParameter("email");
String s1=request.getParameter("monthlyexp");
int mexp=Integer.parseInt(s1);
String s2=request.getParameter("income");
int inc=Integer.parseInt(s2);
String e1=request.getParameter("expense1");
String e2=request.getParameter("expense2");
String e3=request.getParameter("expense3");
String e4=request.getParameter("expense4");
String e5=request.getParameter("expense5");
String e6=request.getParameter("expense6");
String e7=request.getParameter("expense7");
String e8=request.getParameter("expense8");
//String sn="sn1.nextval";
try{
	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","DATASHOP","1234");
	PreparedStatement ps1=con.prepareStatement("insert into user_master values(?,?,?,?,?,?,?)");
	ps1.setString(1,name);
	ps1.setString(2,addr);
	ps1.setString(3,phno);
	ps1.setString(4,pass);
	ps1.setInt(5,mexp);
	ps1.setInt(6,inc );
	ps1.setString(7,email);
	int i=ps1.executeUpdate();
	
	PreparedStatement ps2=con.prepareStatement("insert into expenditure_master values(sn1.nextval,?,?,?,?,?,?,?,?,?)");
	//ps2.setString(1,sn);
	ps2.setString(1,e1);
	ps2.setString(2,e2);
	ps2.setString(3,e3);
	ps2.setString(4,e4);
	ps2.setString(5,e5);
	ps2.setString(6,e6);
	ps2.setString(7,e7);
	ps2.setString(8,e8);
	ps2.setString(9,email);
	int j=ps2.executeUpdate();
	
	if(i>0 && j>0)
	{
		pageContext.forward("welcome.jsp");
	}
	
}catch(Exception e)
{
	e.printStackTrace();
	pageContext.forward("error.jsp");
}




      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
