/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2014-09-06 13:51:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.ArrayList;
import java.sql.ResultSet;
import dao.Dao;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Expense entry</title>\r\n");
      out.write("  <meta name=\"description\" content=\"website description\" />\r\n");
      out.write("  <meta name=\"keywords\" content=\"website keywords, website keywords\" />\r\n");
      out.write("  <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("  <script src=\"jquery-1.6.2.min.js\"></script>\r\n");
      out.write("<script src=\"jquery-ui-1.8.15.custom.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"jquery/jqueryCalendar.css\">\r\n");
      out.write("<script>\r\n");
      out.write("                jQuery(function() {\r\n");
      out.write("                                jQuery( \"#date\" ).datepicker();\r\n");
      out.write("                });\r\n");
      out.write("                </script>\r\n");
      out.write("  <!-- modernizr enables HTML5 elements and feature detects -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/modernizr-1.5.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <div id=\"main\">\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header_user.jsp", out, false);
      out.write("\r\n");
      out.write("    <div id=\"site_content\">\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "photoes.jsp", out, false);
      out.write("\r\n");
      out.write("      <div id=\"sidebar_container\">\r\n");
      out.write("        <div class=\"sidebar\">\r\n");
      out.write("         ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "notice.jsp", out, false);
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"content\">\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <!-- commented\r\n");
      out.write("      \r\n");
      out.write("        <h1>Examples</h1>\r\n");
      out.write("        <p>This page contains examples of all the styled elements available as part of this design. Use this page for reference, whilst you build your website.</p>\r\n");
      out.write("        <h2>Headings</h2>\r\n");
      out.write("        <p>These are the different heading formats:</p>\r\n");
      out.write("        <h1>Heading 1</h1>\r\n");
      out.write("        <h2>Heading 2</h2>\r\n");
      out.write("        <h3>Heading 3</h3>\r\n");
      out.write("        <h4>Heading 4</h4>\r\n");
      out.write("        <h5>Heading 5</h5>\r\n");
      out.write("        <h6>Heading 6</h6>\r\n");
      out.write("        <h2>Text</h2>\r\n");
      out.write("        <p>The following examples show how the text (within '&lt;p&gt;&lt;/p&gt;' tags) will appear:</p>\r\n");
      out.write("        <p><strong>This is an example of bold text</strong></p>\r\n");
      out.write("        <p><i>This is an example of italic text</i></p>\r\n");
      out.write("        <p><a href=\"#\">This is a hyperlink</a></p>\r\n");
      out.write("        <h2>Lists</h2>\r\n");
      out.write("        <p>This is an unordered list:</p>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>Item 1</li>\r\n");
      out.write("          <li>Item 2</li>\r\n");
      out.write("          <li>Item 3</li>\r\n");
      out.write("          <li>Item 4</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>This is an ordered list:</p>\r\n");
      out.write("        <ol>\r\n");
      out.write("          <li>Item 1</li>\r\n");
      out.write("          <li>Item 2</li>\r\n");
      out.write("          <li>Item 3</li>\r\n");
      out.write("          <li>Item 4</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <h2>Images</h2>\r\n");
      out.write("        <p>images can be placed on the left, in the center or on the right:</p>\r\n");
      out.write("        <span class=\"left\"><img src=\"images/graphic.jpg\" alt=\"example graphic\" /></span>\r\n");
      out.write("        <p>\r\n");
      out.write("          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor\r\n");
      out.write("          incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\r\n");
      out.write("          exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute\r\n");
      out.write("          irure dolor in reprehenderit in voluptate velit esse cillum.\r\n");
      out.write("        </p>\r\n");
      out.write("        <span class=\"center\"><img src=\"images/graphic.jpg\" alt=\"example graphic\" /></span>\r\n");
      out.write("        <span class=\"right\"><img src=\"images/graphic.jpg\" alt=\"example graphic\" /></span>\r\n");
      out.write("        <p>\r\n");
      out.write("          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor\r\n");
      out.write("          incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\r\n");
      out.write("          exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute\r\n");
      out.write("          irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla\r\n");
      out.write("          pariatur.\r\n");
      out.write("        </p>\r\n");
      out.write("        <h2>Tables</h2>\r\n");
      out.write("        <p>Tables should be used to display data and not used for laying out your website:</p>\r\n");
      out.write("        <table style=\"width:100%; border-spacing:0;\">\r\n");
      out.write("          <tr><th>Item</th><th>Description</th></tr>\r\n");
      out.write("          <tr><td>Item 1</td><td>Description of Item 1</td></tr>\r\n");
      out.write("          <tr><td>Item 2</td><td>Description of Item 2</td></tr>\r\n");
      out.write("          <tr><td>Item 3</td><td>Description of Item 3</td></tr>\r\n");
      out.write("          <tr><td>Item 4</td><td>Description of Item 4</td></tr>\r\n");
      out.write("        </table> -->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write(" \r\n");
      out.write("        \r\n");
      out.write("        <h2>User's Expence Entry</h2>\r\n");
      out.write("        <fieldset>\r\n");
      out.write("        <form action=\"controllerin.jsp\" method=\"post\">\r\n");
      out.write("          <div class=\"form_settings\">\r\n");
      out.write("            <p><span>Amount</span>\r\n");
      out.write("              <input type=\"text\" name=\"amt\" value=\"\" required=\"required\" /></p>\r\n");
      out.write("            <p><span>Details</span>\r\n");
      out.write("               <textarea rows=\"8\" cols=\"50\" name=\"detail\" required></textarea></p>\r\n");
      out.write("            \r\n");
      out.write("            <p><span>Date</span>\r\n");
      out.write("              <input type=\"date\" name=\"date\"/> \r\n");
      out.write("            </p>\r\n");
      out.write("             <p><span>Select your exp Category</span></p>\r\n");
      out.write("            ");

          String mail=(String)session.getAttribute("id");
          
          
           Dao d=new Dao();
           ArrayList<String> re=new ArrayList();
           re=d.submitExpense(mail);
          

          
      out.write("\r\n");
      out.write("           <span><select name=\"expcat\">\r\n");
      out.write("      \r\n");
      out.write("      ");
  for(int i=0;i<re.size();i++){ 
	  
      out.print("<option>"+re.get(i)+"</option>");
         } 
      out.write("\r\n");
      out.write("              </select>\r\n");
      out.write("                </span>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("            <p>&nbsp;</p>\r\n");
      out.write("            <p>&nbsp;</p>\r\n");
      out.write("            \r\n");
      out.write("             \r\n");
      out.write("              <b> <h6><span>&nbsp;</span>\r\n");
      out.write("                <input class=\"submit\" type=\"submit\" name=\"b1\" value=\"Note\" />\r\n");
      out.write("              </h6>\r\n");
      out.write("          </b>          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("  <!-- javascript at the bottom for fast page loading -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.easing-sooper.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.sooperfish.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.kwicks-1.5.1.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      $('#images').kwicks({\r\n");
      out.write("        max : 600,\r\n");
      out.write("        spacing : 2\r\n");
      out.write("      });\r\n");
      out.write("      $('ul.sf-menu').sooperfish();\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
